import 'package:collection/collection.dart';

/// Supported export formats.
enum AdsImageFormat { jpg, png, gif }

/// Export size/quality presets.
enum AdsQualityPreset { low, medium, high, max }

class AdsExportOptions {
  final AdsImageFormat format;
  final AdsQualityPreset preset;

  /// Optional exact export size override.
  final int? targetWidth;
  final int? targetHeight;

  /// JPEG quality override (0..100). Used only when [format] is [AdsImageFormat.jpg].
  final int? jpgQuality;

  const AdsExportOptions({
    this.format = AdsImageFormat.jpg,
    this.preset = AdsQualityPreset.high,
    this.targetWidth,
    this.targetHeight,
    this.jpgQuality,
  });
}

class AdsScanResult {
  /// Paths captured from camera at maximum supported resolution.
  final List<String> originalImagePaths;

  /// Paths after editor save (if editor was used).
  final List<String>? editedImagePaths;

  /// Optional PDF generated by the native document scanner (if available).
  ///
  /// - Android (ML Kit): returned when RESULT_FORMAT_PDF is enabled.
  /// - iOS (VisionKit): generated from scanned pages.
  final String? pdfPath;

  const AdsScanResult({
    required this.originalImagePaths,
    this.editedImagePaths,
    this.pdfPath,
  });

  @override
  String toString() =>
      'AdsScanResult(original=${originalImagePaths.length}, edited=${editedImagePaths?.length ?? 0}, pdf=${pdfPath != null})';

  @override
  bool operator ==(Object other) {
    return other is AdsScanResult &&
        const ListEquality<String>().equals(originalImagePaths, other.originalImagePaths) &&
        const ListEquality<String>().equals(editedImagePaths, other.editedImagePaths) &&
        pdfPath == other.pdfPath;
  }

  @override
  int get hashCode => Object.hash(
        const ListEquality<String>().hash(originalImagePaths),
        const ListEquality<String>().hash(editedImagePaths),
        pdfPath,
      );
}
